max_width = 100
use_small_heuristics = "Default"

hard_tabs = true
indent_style = "Block"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
fn_single_line = true

newline_style = "Auto"

use_field_init_shorthand = true

wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = false
normalize_doc_attributes = true
format_strings = false

imports_granularity = "Crate"
group_imports = "StdExternalCrate"
